Funcions de ADD, UPDATE i DELETE Usuari
MarcSolde/WallaCHANGE-Backend pull request #1
Opened 2017-03-12 11:27 UTC by MarcSolde

Encara faltaria la part de hashear el pwd i tal, pero de moment es usable. pls reviseu

2017-03-24 16:28 UTC, semuar requested changes
Fem els rename abans d'acceptar el request

2017-03-28 16:52 UTC, MarcSolde commented
Ja està fet el refactor dels noms i s'han corregit els merge conflicts, quan volgueu això va a /develop/

2017-03-28 18:51 UTC, semuar approved these changes

2017-03-28 18:51 UTC, merged

2017-03-28 18:54 UTC, SergiMuAr commented
La deixo pujar ja a develop per treballar amb el tractament d'errors que ha fet el solde com a base.

Tot i així la feature no està acabada.