FB login updated
MarcSolde/WallaCHANGE-Backend pull request #20
Opened 2017-05-15 17:01 UTC by MarcSolde

Canvis al FB login fets

2017-05-15 17:01 UTC, MarcSolde commented
@carlotaprat @sejoDjoseon

2017-05-16 17:20 UTC, sejoDjoseon requested changes
canviar el format de reputacio a real amb un decimal

2017-05-17 15:48 UTC, sejoDjoseon commented
app.use(bodyParser.urlencoded({extended: false})) 
app.use(bodyParser.json()) 
app.use(methodOverride()) 
app.use(function(res, req, next) { 
    res.header("Access-Control-Allow-Origin","*") 
    res.header("Access-Control-Allow-Headers", "Origin,X-Requested-With,Content-Type,Accept") 
    next() 
}) 
 
 
var userModel = require('./model/user.model');   
var userModel = require('./model/user.model'); 
var elemModel = require('./model/element.model'); 
 
var router = express.Router() 

RECUERDA ESTO PURUS

2017-05-17 16:13 UTC, sejoDjoseon approved these changes
Todo PERFECTO, muy bien Purus!

2017-05-17 16:13 UTC, merged